name = "AnisotropicBoltzmannEquation"
uuid = "f63b9913-7a9a-464d-82b9-3e1e536d6db0"
authors = ["Christopher Everett"]
version = "1.0.0-DEV"

[deps]
BoltzmannCollisionIntegral = "20179301-8dfd-43f5-a10b-08fddd2c788a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

 dependencies
